version: "3"

## this dockerfile is just to quickly do docker compose build, and then use things in k8s

services:  
  protoactorwithbatchingonforwarder:
    image: streambatchingwithactormodelsample/protoactorwithbatchingonforwarder:latest
    build:
      context: .
      dockerfile: src/ProtoActorWithBatchingOnForwarder/Dockerfile
