version: "3"

## this dockerfile is just to quickly do docker compose build, and then use things in k8s

services:  
  protoactorsimplifiedwithbatchingonforwarder:
    image: streambatchingwithactormodelsample/protoactorsimplifiedwithbatchingonforwarder:latest
    build:
      context: .
      dockerfile: src/ProtoActorSimplifiedWithBatchingOnForwarder/Dockerfile
