apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  containers:
    - image: mongo:4
      name: mongo
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "user"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "pass"
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  type: LoadBalancer # so we can connect from outside the cluster to inspect
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017